### PR TITLE
WIP - First integration blog -> index working

### PR DESCRIPTION
**Pull request by juampick**
Only a WIP, but index endpoint (getting post from **/api/blog** working 💃 )
@mravinale

### CODE REVIEW

**Comment by mravinale** [comment]
awesome!!

**Comment by AlphaGit** [comment]
This commit includes a bunch of commented out routes and implementations. Is that correct? (I understand that this is a WIP, but should it be merged in this state if it may change?)

Also, there's a `/juampi` route implemented. Is that intended to be merged too?

**Comment by AlphaGit** [comment]
Ugh, I just noticed I was looking at a training repository. I thought this was a main product repository. You can disregard my comments (but if you want to respond and give me context, I'd appreciate that more!)

**Comment by mravinale** [comment]
@AlphaGit yes, I think, @juampick will work today on cleaning this and finish this implementation

**Pull request merged**
